# pattern regex flavor: re2: https://github.com/google/re2/wiki/Syntax
# validator (select flavor golang): https://regex101.com/
filenames:
  - pattern: .+\.log
    minSizeMb: 0
    olderThanDays: 2
    action: print
  - pattern: omaga
    minSizeMb: 0
    olderThanDays: 0
    action: delete
folders:
  - name: "."